svc:
  full_contact:
    name: Full Contact
    keys: 
      api: provided
    
    triggers:
    
    actions:
      search_by_email:
        name: Search by Email
        execute: fbr
        end_point: https://api.fullcontact.com/v2/person.json
        params: 
          email: m
        request: get

      search_by_fb_id: 
        name: Search by Facebook
        execute: fbr
        end_point: https://api.fullcontact.com/v2/person.json
        params: 
          email: m
        request: get
      search_by_twitter_id:  
        name: Search by Twitter ID
        execute: fbr
        end_point: https://api.fullcontact.com/v2/person.json
        params: 
          email: m
        request: get

