svc:
  gmail:
    keys: 
      api: 
    triggers: 
      [ 
        { 
          name: Send Email, 
          endpoint: "TODO", 
          params: {}
        },
        { 
          name: Receive Email, 
          endpoint: "TODO", 
          params: {}
        }
      ]
