'$b': 'browser'
'$bv': 'browser_version'
'$os' : 'operating_system'
'$r' : 'referrer'
'$r[h]' : 'referrer[host]'
'$r[p]' : 'referrer[path]'
'$r[n]' : 'referrer[name]'
'$d' : 'device'
'$d[t]' : 'device[type]'
'$d[n]' : 'device[name]'
'$s' : 'screen'
'$s[h]' : 'screen[height]'
'$s[w]' : 'screen[width]'
'$v' : 'viewport'
'$v[h]' : 'viewport[height]'
'$v[w]' : 'viewport[width]'
'$s' : 'search'
'$s[e]' : 'search[engine]'
'$s[q]' : 'search[query]'
'$c' : 'country'
'$l' : 'language'
'$p' : 'plugins'
'$t' : 'timezone'
'$dls' : 'day_light_saving'

