rbT.templateLib = {
	 	  'bottombar.generic.fblike':'rbTemplBottombarGenericFblikeHTML',
	 	  'topbar.generic.normal':'rbTemplTopbarGenericNormalHTML',
	 	  'chat.generic.normal':'rbTemplChatGenericNormalHTML',
	 	  'topbar.generic.twitterfollow':'rbTemplTopbarGenericTwitterfollowHTML',
	 	  'bottombar.generic.twitterfollow':'rbTemplBottombarGenericTwitterfollowHTML',
	 	  'topbar.generic.fblike':'rbTemplTopbarGenericFblikeHTML',
	 	  'bottombar.generic.twittershare':'rbTemplBottombarGenericTwittershareHTML',
	 	  'modal.generic.normal':'rbTemplModalGenericNormalHTML',
	 	  'bottombar.generic.normal':'rbTemplBottombarGenericNormalHTML',
	 	  'topbar.generic.twittershare':'rbTemplTopbarGenericTwittershareHTML'
 
 	 	 	 }; 



 rbT.templateArgs = {
	 	  'bottombar.generic.fblike':[
	 	 	 	 	 	 {key:'rb.t.cr.textColor ',value:'#F2F0F0'},
	 	 	 	 	 	 {key:'rb.t.nr.textFontsize',value:'15'},
	 	 	 	 	 	 {key:'rb.t.ft.textFontfamily',value:'Arial'},
	 	 	 	 	 	 {key:'rb.f.nr.baseZindex',value:'1000'},
	 	 	 	 	 	 {key:'rb.t.nr.baseWidth',value:'100'},
	 	 	 	 	 	 {key:'rb.t.nr.baseHeight',value:'40'},
	 	 	 	 	 	 {key:'rb.t.cr.baseBgColor',value:'#3C5891'},
	 	 	 	 	 	 {key:'rb.t.an.baseTextalign',value:'center'},
	 	 	 	 	 	 {key:'rb.t.sg.textLeft',value:'Hello Hello'},
	 	 	 	 	 	 {key:'rb.t.ul.facebookPage',value:'http://www.google.com'},
	 	 	 	 	 	 {key:'rb.t.sg.textRight',value:'Hello Hello'},
	 	 	 	 	 	 {key:'rb.t.ul.helpLink',value:'http://www.rulebot.com'},
	 	 	 	 	 ],
	 	  'topbar.generic.normal':[
	 	 	 	 	 	 {key:'rb.t.cr.textColor ',value:'#333'},
	 	 	 	 	 	 {key:'rb.t.nr.textFontsize',value:'15'},
	 	 	 	 	 	 {key:'rb.t.ft.textFontfamily',value:'Arial'},
	 	 	 	 	 	 {key:'rb.f.nr.baseZindex',value:'100'},
	 	 	 	 	 	 {key:'rb.t.nr.baseWidth',value:'100'},
	 	 	 	 	 	 {key:'rb.t.nr.baseHeight',value:'40'},
	 	 	 	 	 	 {key:'rb.t.cr.baseBgColor',value:'#DCDCDC'},
	 	 	 	 	 	 {key:'rb.t.an.baseTextalign',value:'center'},
	 	 	 	 	 	 {key:'rb.t.sg.textLeft',value:'Hello Hello Hello Hello'},
	 	 	 	 	 	 {key:'rb.t.nr.btnFontSize',value:'14'},
	 	 	 	 	 	 {key:'rb.t.cr.btnBgColor',value:'#548AC7'},
	 	 	 	 	 	 {key:'rb.t.cr.btnColor',value:'white'},
	 	 	 	 	 	 {key:'rb.t.ul.btnLink',value:'http://www.google.com'},
	 	 	 	 	 	 {key:'rb.t.sg.btnLable',value:'Click'},
	 	 	 	 	 	 {key:'rb.t.sg.textRight',value:'Hello Hello'},
	 	 	 	 	 	 {key:'rb.t.ul.helpLink',value:'http://www.rulebot.com'},
	 	 	 	 	 ],
	 	  'chat.generic.normal':[
	 	 	 	 	 	 {key:'rb.t.sg.olarkIdentity',value:'\'6679-845-10-6199\''},
	 	 	 	 	 ],
	 	  'topbar.generic.twitterfollow':[
	 	 	 	 	 	 {key:'rb.t.cr.textColor ',value:'white'},
	 	 	 	 	 	 {key:'rb.t.nr.textFontsize',value:'17'},
	 	 	 	 	 	 {key:'rb.t.cr.textShadow',value:'black'},
	 	 	 	 	 	 {key:'rb.t.ft.textFontfamily',value:'Arial'},
	 	 	 	 	 	 {key:'rb.f.nr.baseZindex',value:'1000'},
	 	 	 	 	 	 {key:'rb.t.nr.baeWidth',value:'100'},
	 	 	 	 	 	 {key:'rb.t.nr.baseHeight',value:'50'},
	 	 	 	 	 	 {key:'rb.t.cr.baeBgColor',value:'#0B8AB8'},
	 	 	 	 	 	 {key:'rb.t.an.baseTextalign',value:'center'},
	 	 	 	 	 	 {key:'rb.t.sg.textLeft',value:'Hello Hello'},
	 	 	 	 	 	 {key:'rb.t.sg.twitterAccount',value:'@actwitty'},
	 	 	 	 	 	 {key:'rb.t.sg.twitterAccount',value:'@actwitty'},
	 	 	 	 	 	 {key:'rb.t.sg.textRight',value:'Hello Hello'},
	 	 	 	 	 	 {key:'rb.t.ul.helpLink',value:'http://www.rulebot.com'},
	 	 	 	 	 ],
	 	  'bottombar.generic.twitterfollow':[
	 	 	 	 	 	 {key:'rb.t.cr.textColor ',value:'white'},
	 	 	 	 	 	 {key:'rb.t.nr.textFontsize',value:'17'},
	 	 	 	 	 	 {key:'rb.t.cr.textShadow',value:'black'},
	 	 	 	 	 	 {key:'rb.t.ft.textFontfamily',value:'Arial'},
	 	 	 	 	 	 {key:'rb.f.nr.baseZindex',value:'1000'},
	 	 	 	 	 	 {key:'rb.t.nr.baeWidth',value:'100'},
	 	 	 	 	 	 {key:'rb.t.nr.baseHeight',value:'50'},
	 	 	 	 	 	 {key:'rb.t.cr.baeBgColor',value:'#0B8AB8'},
	 	 	 	 	 	 {key:'rb.t.an.baseTextalign',value:'center'},
	 	 	 	 	 	 {key:'rb.t.sg.textLeft',value:'Hello Hello'},
	 	 	 	 	 	 {key:'rb.t.sg.twitterAccount',value:'@actwitty'},
	 	 	 	 	 	 {key:'rb.t.sg.twitterAccount',value:'@actwitty'},
	 	 	 	 	 	 {key:'rb.t.sg.textRight',value:'Hello Hello'},
	 	 	 	 	 	 {key:'rb.t.ul.helpLink',value:'http://www.rulebot.com'},
	 	 	 	 	 ],
	 	  'topbar.generic.fblike':[
	 	 	 	 	 	 {key:'rb.t.cr.textColor ',value:'#F2F0F0'},
	 	 	 	 	 	 {key:'rb.t.nr.textFontsize',value:'16'},
	 	 	 	 	 	 {key:'rb.t.ft.textFontfamily',value:'Arial'},
	 	 	 	 	 	 {key:'rb.f.nr.baseZindex',value:'1000'},
	 	 	 	 	 	 {key:'rb.t.nr.baseWidth',value:'100'},
	 	 	 	 	 	 {key:'rb.t.nr.baseHeight',value:'40'},
	 	 	 	 	 	 {key:'rb.t.cr.baseBgColor',value:'#3C5891'},
	 	 	 	 	 	 {key:'rb.t.an.baseTextalign',value:'center'},
	 	 	 	 	 	 {key:'rb.t.sg.textLeft',value:'Hello Hello'},
	 	 	 	 	 	 {key:'rb.t.ul.facebookPage=%%http://www.google.com',value:''},
	 	 	 	 	 	 {key:'rb.t.sg.textRight',value:'Hello Hello'},
	 	 	 	 	 	 {key:'rb.t.ul.helpLink',value:'http://www.google.com'},
	 	 	 	 	 ],
	 	  'bottombar.generic.twittershare':[
	 	 	 	 	 	 {key:'rb.t.cr.textColor ',value:'white'},
	 	 	 	 	 	 {key:'rb.t.nr.textFontsize',value:'17'},
	 	 	 	 	 	 {key:'rb.t.cr.textShadow',value:'black'},
	 	 	 	 	 	 {key:'rb.t.ft.textFontfamily',value:'Arial'},
	 	 	 	 	 	 {key:'rb.f.nr.baseZindex',value:'1000'},
	 	 	 	 	 	 {key:'rb.t.nr.baeWidth',value:'100'},
	 	 	 	 	 	 {key:'rb.t.nr.baseHeight',value:'50'},
	 	 	 	 	 	 {key:'rb.t.cr.baeBgColor',value:'#0B8AB8'},
	 	 	 	 	 	 {key:'rb.t.an.baseTextalign',value:'center'},
	 	 	 	 	 	 {key:'rb.t.sg.leftText',value:'Hello Hello'},
	 	 	 	 	 	 {key:'rb.t.sg.twitterSharetext',value:'Twteet please'},
	 	 	 	 	 	 {key:'rb.t.sg.rightText',value:'Hello Hello'},
	 	 	 	 	 	 {key:'rb.t.ul.helpLink',value:''},
	 	 	 	 	 ],
	 	  'modal.generic.normal':[
	 	 	 	 	 	 {key:'rb.f.nr.transBlockZindex',value:'1000'},
	 	 	 	 	 	 {key:'rb.f.nr.baseZindex',value:'1005'},
	 	 	 	 	 	 {key:'rb.t.cr.baseBgColor',value:'white'},
	 	 	 	 	 	 {key:'rb.t.cr.headingBgColor',value:'#e7e7e7'},
	 	 	 	 	 	 {key:'rb.t.cr.modalHeadingColor',value:'#525252'},
	 	 	 	 	 	 {key:'rb.t.nr.modalHeadingFontsize',value:'20'},
	 	 	 	 	 	 {key:'rb.t.ft.headingFontfamily',value:'Arial'},
	 	 	 	 	 	 {key:'rb.t.cr.modalHeadingTextShadow#6e6e6e',value:''},
	 	 	 	 	 	 {key:'rb.t.sg.modalHeadingText',value:'This is the Heading '},
	 	 	 	 	 	 {key:'rb.t.cr.modalTextColor',value:'#525252'},
	 	 	 	 	 	 {key:'rb.t.nr.modalTextFontsize',value:'12'},
	 	 	 	 	 	 {key:'rb.t.ft.textFontfamily',value:'Arial'},
	 	 	 	 	 	 {key:'rb.t.sg.modalText',value:'Hello Hello Hello Hello Hello hello heello bjashsdgfsdhvfhsdvcfhsdvhcsd hvhvchjsdvchjsdvchjvsdchvsdhvcjhsdvjvh '},
	 	 	 	 	 	 {key:'rb.t.sg.modalImgPath',value:'../../../images/rails.png'},
	 	 	 	 	 	 {key:'rb.t.cr.buttonBgColor',value:'#3B5998'},
	 	 	 	 	 	 {key:'rb.t.ul.modalBtnLink',value:'http://www.google.com'},
	 	 	 	 	 	 {key:'rb.t.sg.modalBtnLable',value:'Click'},
	 	 	 	 	 ],
	 	  'bottombar.generic.normal':[
	 	 	 	 	 	 {key:'rb.t.cr.textColor ',value:'#333'},
	 	 	 	 	 	 {key:'rb.t.nr.textFontsize',value:'15'},
	 	 	 	 	 	 {key:'rb.t.ft.textFontfamily',value:'Arial'},
	 	 	 	 	 	 {key:'rb.f.nr.baseZindex',value:'100'},
	 	 	 	 	 	 {key:'rb.t.nr.baseWidth',value:'100'},
	 	 	 	 	 	 {key:'rb.t.nr.baseHeight',value:'40'},
	 	 	 	 	 	 {key:'rb.t.cr.baseBgColor',value:'#DCDCDC'},
	 	 	 	 	 	 {key:'rb.t.an.baseTextalign',value:'center'},
	 	 	 	 	 	 {key:'rb.t.sg.textLeft',value:'Hello Hello'},
	 	 	 	 	 	 {key:'rb.t.nr.btnFontSize',value:'14'},
	 	 	 	 	 	 {key:'rb.t.cr.btnBgColor',value:'#548AC7'},
	 	 	 	 	 	 {key:'rb.t.cr.btnColor',value:'white'},
	 	 	 	 	 	 {key:'rb.t.ul.btnLink',value:'http://www.google.com'},
	 	 	 	 	 	 {key:'rb.t.sg.btnLable',value:'Click'},
	 	 	 	 	 	 {key:'rb.t.sg.textRight',value:'Hello Hello'},
	 	 	 	 	 	 {key:'rb.t.ul.helpLink',value:'http://www.rulebot.com'},
	 	 	 	 	 ],
	 	  'topbar.generic.twittershare':[
	 	 	 	 	 	 {key:'rb.t.cr.textColor ',value:'white'},
	 	 	 	 	 	 {key:'rb.t.nr.textFontsize',value:'17'},
	 	 	 	 	 	 {key:'rb.t.cr.textShadow',value:'black'},
	 	 	 	 	 	 {key:'rb.t.ft.textFontfamily',value:'Arial'},
	 	 	 	 	 	 {key:'rb.f.nr.baseZindex',value:'1000'},
	 	 	 	 	 	 {key:'rb.t.nr.baeWidth',value:'100'},
	 	 	 	 	 	 {key:'rb.t.nr.baseHeight',value:'50'},
	 	 	 	 	 	 {key:'rb.t.cr.baeBgColor',value:'#0B8AB8'},
	 	 	 	 	 	 {key:'rb.t.an.baseTextalign',value:'center'},
	 	 	 	 	 	 {key:'rb.t.sg.leftText',value:'Hello Hello'},
	 	 	 	 	 	 {key:'rb.t.sg.twitterSharetext',value:'Tweet Please'},
	 	 	 	 	 	 {key:'rb.t.sg.rightText',value:'Hello Hello'},
	 	 	 	 	 	 {key:'rb.t.ul.helpLink',value:''},
	 	 	 	 	 ]
 	 	 	 	 }; 
 
