rbT.templateLib = {
	 	  'bottombar.generic.fblike':'rbTemplBottombarGenericFblikeHTML',
	 	  'topbar.generic.normal':'rbTemplTopbarGenericNormalHTML',
	 	  'chat.generic.normal':'rbTemplChatGenericNormalHTML',
	 	  'topbar.generic.twitterfollow':'rbTemplTopbarGenericTwitterfollowHTML',
	 	  'bottombar.generic.twitterfollow':'rbTemplBottombarGenericTwitterfollowHTML',
	 	  'topbar.generic.fblike':'rbTemplTopbarGenericFblikeHTML',
	 	  'bottombar.generic.twittershare':'rbTemplBottombarGenericTwittershareHTML',
	 	  'modal.generic.normal':'rbTemplModalGenericNormalHTML',
	 	  'bottombar.generic.normal':'rbTemplBottombarGenericNormalHTML',
	 	  'topbar.generic.twittershare':'rbTemplTopbarGenericTwittershareHTML'
 
 	 	 	 }; 



 rbT.templateName = {
	 			'bottombar.generic.fblike':'Facebook Like Bottombar',
	 			'topbar.generic.normal':'Normal Topbar',
	 			'chat.generic.normal':'Chat Window',
	 			'topbar.generic.twitterfollow':'Twitter Follow Topbar',
	 			'bottombar.generic.twitterfollow':'Twitter Follow Bottombar',
	 			'topbar.generic.fblike':'Facebook Like Topbar',
	 			'bottombar.generic.twittershare':'Twitter Share Bottombar',
	 			'modal.generic.normal':'Modal Window',
	 			'bottombar.generic.normal':'Normal Bottombar',
	 			'topbar.generic.twittershare':'Twitter Share Topbar'
 	 	 	 	 }; 



 rbT.templateArgs = {
	 	  'bottombar.generic.fblike':{
	 	 	 	 	 	 'rb.t.cr.textColor ':'#F2F0F0',
	 	 	 	 	 	 'rb.t.nr.textFontsize':'15',
	 	 	 	 	 	 'rb.t.ft.textFontfamily':'Arial',
	 	 	 	 	 	 'rb.t.ft.textFontWeight':'bold',
	 	 	 	 	 	 'rb.f.nr.baseZindex':'1000',
	 	 	 	 	 	 'rb.t.nr.baseWidth':'100',
	 	 	 	 	 	 'rb.t.nr.baseHeight':'40',
	 	 	 	 	 	 'rb.t.cr.baseBgColor':'#3C5891',
	 	 	 	 	 	 'rb.t.an.baseTextalign':'center',
	 	 	 	 	 	 'rb.t.sg.textLeft':'Hello Hello',
	 	 	 	 	 	 'rb.t.ul.facebookPage':'http://www.google.com',
	 	 	 	 	 	 'rb.t.sg.textRight':'Hello Hello',
	 	 	 	 	 	 'rb.t.nr.durationOfDisplay':'10'
	 	 	 	 	 },
	 	  'topbar.generic.normal':{
	 	 	 	 	 	 'rb.t.cr.textColor ':'#333',
	 	 	 	 	 	 'rb.t.nr.textFontsize':'15',
	 	 	 	 	 	 'rb.t.ft.textFontfamily':'Arial',
	 	 	 	 	 	 'rb.t.ft.textFontWeight':'bold',
	 	 	 	 	 	 'rb.f.nr.baseZindex':'100',
	 	 	 	 	 	 'rb.t.nr.baseWidth':'100',
	 	 	 	 	 	 'rb.t.nr.baseHeight':'40',
	 	 	 	 	 	 'rb.t.cr.baseBgColor':'#DCDCDC',
	 	 	 	 	 	 'rb.t.an.baseTextalign':'center',
	 	 	 	 	 	 'rb.t.sg.textLeft':'Hello Hello Hello Hello',
	 	 	 	 	 	 'rb.t.nr.btnFontSize':'14',
	 	 	 	 	 	 'rb.t.cr.btnBgColor':'#548AC7',
	 	 	 	 	 	 'rb.t.cr.btnColor':'white',
	 	 	 	 	 	 'rb.t.ul.btnLink':'http://www.google.com',
	 	 	 	 	 	 'rb.t.sg.btnLable':'Click',
	 	 	 	 	 	 'rb.t.sg.textRight':'Hello Hello',
	 	 	 	 	 	 'rb.t.nr.durationOfDisplay':'100'
	 	 	 	 	 },
	 	  'chat.generic.normal':{
	 	 	 	 	 	 'rb.t.sg.olarkIdentity':'\'6679-845-10-6199\'',
	 	 	 	 	 	 'rb.t.nr.durationOfDisplay':'10'
	 	 	 	 	 },
	 	  'topbar.generic.twitterfollow':{
	 	 	 	 	 	 'rb.t.cr.textColor ':'white',
	 	 	 	 	 	 'rb.t.nr.textFontsize':'17',
	 	 	 	 	 	 'rb.t.cr.textShadow':'black',
	 	 	 	 	 	 'rb.t.ft.textFontfamily':'Arial',
	 	 	 	 	 	 'rb.t.ft.textFontWeight':'bold',
	 	 	 	 	 	 'rb.f.nr.baseZindex':'1000',
	 	 	 	 	 	 'rb.t.nr.baeWidth':'100',
	 	 	 	 	 	 'rb.t.nr.baseHeight':'50',
	 	 	 	 	 	 'rb.t.cr.baeBgColor':'#0B8AB8',
	 	 	 	 	 	 'rb.t.an.baseTextalign':'center',
	 	 	 	 	 	 'rb.t.sg.textLeft':'Hello Hello',
	 	 	 	 	 	 'rb.t.sg.twitterAccountLink':'@actwitty',
	 	 	 	 	 	 'rb.t.sg.twitterAccountLable':'@actwitty',
	 	 	 	 	 	 'rb.t.sg.textRight':'Hello Hello',
	 	 	 	 	 	 'rb.t.nr.durationOfDisplay':'100'
	 	 	 	 	 },
	 	  'bottombar.generic.twitterfollow':{
	 	 	 	 	 	 'rb.t.cr.textColor ':'white',
	 	 	 	 	 	 'rb.t.nr.textFontsize':'17',
	 	 	 	 	 	 'rb.t.cr.textShadow':'black',
	 	 	 	 	 	 'rb.t.ft.textFontfamily':'Arial',
	 	 	 	 	 	 'rb.t.ft.textFontWeight':'bold',
	 	 	 	 	 	 'rb.f.nr.baseZindex':'1000',
	 	 	 	 	 	 'rb.t.nr.baeWidth':'100',
	 	 	 	 	 	 'rb.t.nr.baseHeight':'50',
	 	 	 	 	 	 'rb.t.cr.baeBgColor':'#0B8AB8',
	 	 	 	 	 	 'rb.t.an.baseTextalign':'center',
	 	 	 	 	 	 'rb.t.sg.textLeft':'Hello Hello',
	 	 	 	 	 	 'rb.t.sg.twitterAccountLink':'@actwitty',
	 	 	 	 	 	 'rb.t.sg.twitterAccountLable':'@actwitty',
	 	 	 	 	 	 'rb.t.sg.textRight':'Hello Hello',
	 	 	 	 	 	 'rb.t.nr.durationOfDisplay':'100'
	 	 	 	 	 },
	 	  'topbar.generic.fblike':{
	 	 	 	 	 	 'rb.t.cr.textColor ':'#F2F0F0',
	 	 	 	 	 	 'rb.t.nr.textFontsize':'16',
	 	 	 	 	 	 'rb.t.ft.textFontfamily':'Arial',
	 	 	 	 	 	 'rb.t.ft.textFontWeight':'bold',
	 	 	 	 	 	 'rb.f.nr.baseZindex':'1000',
	 	 	 	 	 	 'rb.t.nr.baseWidth':'100',
	 	 	 	 	 	 'rb.t.nr.baseHeight':'40',
	 	 	 	 	 	 'rb.t.cr.baseBgColor':'#3C5891',
	 	 	 	 	 	 'rb.t.an.baseTextalign':'center',
	 	 	 	 	 	 'rb.t.sg.textLeft':'Hello Hello',
	 	 	 	 	 	 'rb.t.ul.facebookPage=%%http://www.google.com':'',
	 	 	 	 	 	 'rb.t.sg.textRight':'Hello Hello',
	 	 	 	 	 	 'rb.t.nr.durationOfDisplay':'100'
	 	 	 	 	 },
	 	  'bottombar.generic.twittershare':{
	 	 	 	 	 	 'rb.t.cr.textColor ':'white',
	 	 	 	 	 	 'rb.t.nr.textFontsize':'17',
	 	 	 	 	 	 'rb.t.cr.textShadow':'black',
	 	 	 	 	 	 'rb.t.ft.textFontfamily':'Arial',
	 	 	 	 	 	 'rb.t.ft.textFontWeight':'bold',
	 	 	 	 	 	 'rb.f.nr.baseZindex':'1000',
	 	 	 	 	 	 'rb.t.nr.baeWidth':'100',
	 	 	 	 	 	 'rb.t.nr.baseHeight':'50',
	 	 	 	 	 	 'rb.t.cr.baeBgColor':'#0B8AB8',
	 	 	 	 	 	 'rb.t.an.baseTextalign':'center',
	 	 	 	 	 	 'rb.t.sg.leftText':'Hello Hello',
	 	 	 	 	 	 'rb.t.sg.twitterSharetext':'Twteet please',
	 	 	 	 	 	 'rb.t.sg.rightText':'Hello Hello',
	 	 	 	 	 	 'rb.t.nr.durationOfDisplay':'10'
	 	 	 	 	 },
	 	  'modal.generic.normal':{
	 	 	 	 	 	 'rb.f.nr.transBlockZindex':'1000',
	 	 	 	 	 	 'rb.f.nr.baseZindex':'1005',
	 	 	 	 	 	 'rb.t.cr.baseBgColor':'white',
	 	 	 	 	 	 'rb.t.cr.headingBgColor':'#e7e7e7',
	 	 	 	 	 	 'rb.t.cr.modalHeadingColor':'#525252',
	 	 	 	 	 	 'rb.t.nr.modalHeadingFontsize':'20',
	 	 	 	 	 	 'rb.t.ft.headingFontfamily':'Arial',
	 	 	 	 	 	 'rb.t.cr.modalHeadingTextShadow#6e6e6e':'',
	 	 	 	 	 	 'rb.t.sg.modalHeadingText':'This is the Heading ',
	 	 	 	 	 	 'rb.t.cr.modalTextColor':'#525252',
	 	 	 	 	 	 'rb.t.nr.modalTextFontsize':'12',
	 	 	 	 	 	 'rb.t.ft.textFontfamily':'Arial',
	 	 	 	 	 	 'rb.t.sg.modalText':'Hello Hello Hello Hello Hello hello heello bjashsdgfsdhvfhsdvcfhsdvhcsd hvhvchjsdvchjsdvchjvsdchvsdhvcjhsdvjvh ',
	 	 	 	 	 	 'rb.t.sg.modalImgPath':'../../../images/rails.png',
	 	 	 	 	 	 'rb.t.cr.buttonBgColor':'#3B5998',
	 	 	 	 	 	 'rb.t.ul.modalBtnLink':'http://www.google.com',
	 	 	 	 	 	 'rb.t.sg.modalBtnLable':'Click',
	 	 	 	 	 	 'rb.t.nr.durationOfDisplay':'10'
	 	 	 	 	 },
	 	  'bottombar.generic.normal':{
	 	 	 	 	 	 'rb.t.cr.textColor ':'#333',
	 	 	 	 	 	 'rb.t.nr.textFontsize':'15',
	 	 	 	 	 	 'rb.t.ft.textFontfamily':'Arial',
	 	 	 	 	 	 'rb.t.ft.textFontWeight':'bold',
	 	 	 	 	 	 'rb.f.nr.baseZindex':'100',
	 	 	 	 	 	 'rb.t.nr.baseWidth':'100',
	 	 	 	 	 	 'rb.t.nr.baseHeight':'40',
	 	 	 	 	 	 'rb.t.cr.baseBgColor':'#DCDCDC',
	 	 	 	 	 	 'rb.t.an.baseTextalign':'center',
	 	 	 	 	 	 'rb.t.sg.textLeft':'Hello Hello',
	 	 	 	 	 	 'rb.t.nr.btnFontSize':'14',
	 	 	 	 	 	 'rb.t.cr.btnBgColor':'#548AC7',
	 	 	 	 	 	 'rb.t.cr.btnColor':'white',
	 	 	 	 	 	 'rb.t.ul.btnLink':'http://www.google.com',
	 	 	 	 	 	 'rb.t.sg.btnLable':'Click',
	 	 	 	 	 	 'rb.t.sg.textRight':'Hello Hello',
	 	 	 	 	 	 'rb.t.nr.durationOfDisplay':'10'
	 	 	 	 	 },
	 	  'topbar.generic.twittershare':{
	 	 	 	 	 	 'rb.t.cr.textColor ':'white',
	 	 	 	 	 	 'rb.t.nr.textFontsize':'17',
	 	 	 	 	 	 'rb.t.cr.textShadow':'black',
	 	 	 	 	 	 'rb.t.ft.textFontfamily':'Arial',
	 	 	 	 	 	 'rb.t.ft.textFontWeight':'bold',
	 	 	 	 	 	 'rb.f.nr.baseZindex':'1000',
	 	 	 	 	 	 'rb.t.nr.baeWidth':'100',
	 	 	 	 	 	 'rb.t.nr.baseHeight':'50',
	 	 	 	 	 	 'rb.t.cr.baeBgColor':'#0B8AB8',
	 	 	 	 	 	 'rb.t.an.baseTextalign':'center',
	 	 	 	 	 	 'rb.t.sg.leftText':'Hello Hello',
	 	 	 	 	 	 'rb.t.sg.twitterSharetext':'Tweet Please',
	 	 	 	 	 	 'rb.t.sg.rightText':'Hello Hello',
	 	 	 	 	 	 'rb.t.nr.durationOfDisplay':'100'
	 	 	 	 	 }
 	 	 	 	 }; 
 
